import * as vscode from 'vscode';
import { DatabaseService } from '../services/DatabaseService';

export class SchemaDocumentProvider implements vscode.TextDocumentContentProvider {
    public static readonly scheme = 'mybatis-schema';
    private dbService: DatabaseService;

    constructor(dbService: DatabaseService) {
        this.dbService = dbService;
    }

    async provideTextDocumentContent(uri: vscode.Uri): Promise<string> {
        let tableName = uri.path.replace(/^\//, ''); // Remove leading slash
        // Remove .md extension if present
        if (tableName.endsWith('.md')) {
            tableName = tableName.slice(0, -3);
        }

        const columns = await this.dbService.getTableSchema(tableName);
        const ddl = await this.dbService.getCreateTableStatement(tableName);

        if (!columns || columns.length === 0) {
            return `Table '${tableName}' not found or has no columns.`;
        }

        let md = `# Table Schema: ${tableName}\n\n`;

        // DDL Section
        if (ddl) {
            md += `## DDL\n\n`;
            md += '```sql\n';
            md += ddl + '\n';
            md += '```\n\n';
        }

        // Columns Section
        md += `## Columns\n\n`;
        md += `| Field | Type | Key | Null | Default | Comment |\n`;
        md += `|---|---|---|---|---|---|\n`;

        columns.forEach(col => {
            const key = col.Key === 'PRI' ? '🔑 PK' : (col.Key === 'MUL' ? '🗝️ MUL' : (col.Key === 'UNI' ? '🌟 UNI' : ''));
            const nullable = col.Null === 'YES' ? '✅' : '❌';
            const def = col.Default === null ? 'NULL' : `\`${col.Default}\``;
            const comment = col.Comment || '';

            // Formatting types for readability
            let type = col.Type;
            if (type.includes('char') || type.includes('text')) {
                type = `🔤 ${type}`;
            } else if (type.includes('int') || type.includes('dec') || type.includes('float') || type.includes('double')) {
                type = `🔢 ${type}`;
            } else if (type.includes('date') || type.includes('time')) {
                type = `📅 ${type}`;
            }

            md += `| **${col.Field}** | ${type} | ${key} | ${nullable} | ${def} | ${comment} |\n`;
        });

        md += `\n\n---\n*Generated by MyBatis Toolkit Pro*`;
        return md;
    }
}
